### ISSUE TITLE
Commands for music related things

### ISSUE THREAD

**Issue by nicolaei** [edmproduction/EDMProduction_IRC_Bot#2]
<b>Command 1:</b>
<i>Syntax</i>: <code>@frequency <frequency></code>

This command will show the corresponding note for <frequency>.

<b>Command 2:</b>
<i>Syntax</i>: <code>@note <note></code>

This command will show the corresponding frequency for <note>

**Comment by sudocurse** [comment]
what do you think about <code>@scale <key></code>?

**Comment by nicolaei** [comment]
Sounds like a good idea! Though we have to include modes, so like this instead: <code>@scale <key> <mode></code>

**Comment by sudocurse** [comment]
Maybe make <code><mode></code> optional, and omitted defaults to the scale's first mode?

**Comment by sudocurse** [comment]
Instead of adding <code>[mode]</code> perhaps it's sufficient to just include different modes as types of scales. 

Also important to note for implementation: do we want scales other than standard major/minor based ones? There are [some weird scales out there](http://en.wikipedia.org/wiki/List_of_musical_scales_and_modes).

**Comment by nicolaei** [comment]
I think the best idea is to only include scales and modes that are more common in electronic music, it is a electronic music based channel/subreddit after all.

**Comment by nicolaei** [comment]
Added with commit 9889663154ee4bdfeda1074ed7af02abe022663d and d568b0c8befa7b0f25ad95b25174a595980b8578
